In [1]:
# Import the dependencies
import pandas as pd
import numpy as np
from sklearn import datasets

In [2]:
# Load the run_or_walk dataset
df = pd.read_csv("covid_impact_on_airport_traffic.csv")

In [3]:
# Show the dimensions of the dataframe

df.shape

(7247, 11)

In [5]:
# Explore the diabetes dataset

df.head(15)

,AggregationMethod,Date,Version,AirportName,PercentOfBaseline,Centroid,City,State,ISO_3166_2,Country,Geography
0,Daily,2020-04-03,1.0,Kingsford Smith,64,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
1,Daily,2020-04-13,1.0,Kingsford Smith,29,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
2,Daily,2020-07-10,1.0,Kingsford Smith,54,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
3,Daily,2020-09-02,1.0,Kingsford Smith,18,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
4,Daily,2020-10-31,1.0,Kingsford Smith,22,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
5,Daily,2020-04-14,1.0,Kingsford Smith,59,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
6,Daily,2020-05-14,1.0,Kingsford Smith,59,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
7,Daily,2020-07-04,1.0,Kingsford Smith,48,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
8,Daily,2020-08-05,1.0,Kingsford Smith,20,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
9,Daily,2020-11-20,1.0,Kingsford Smith,27,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
10,Daily,2020-06-21,1.0,Kingsford Smith,46,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
11,Daily,2020-08-10,1.0,Kingsford Smith,19,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
12,Daily,2020-10-01,1.0,Kingsford Smith,19,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
13,Daily,2020-10-21,1.0,Kingsford Smith,20,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."
14,Daily,2020-11-05,1.0,Kingsford Smith,16,POINT(151.180087713813 -33.9459774986125),Sydney,New South Wales,AU,Australia,"POLYGON((151.164354085922 -33.9301772341877, 1..."

In [4]:
# Show the structure of the dataframe

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7247 entries, 0 to 7246
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AggregationMethod  7247 non-null   object
 1   Date               7247 non-null   object
 2   Version            7247 non-null   float64
 3   AirportName        7247 non-null   object
 4   PercentOfBaseline  7247 non-null   int64
 5   Centroid           7247 non-null   object
 6   City               7247 non-null   object
 7   State              7247 non-null   object
 8   ISO_3166_2         7247 non-null   object
 9   Country            7247 non-null   object
 10  Geography          7247 non-null   object
dtypes: float64(1), int64(1), object(9)
memory usage: 622.9+ KB

In [6]:
# Convert Date column from object type to datetime

df["Date"] = pd.to_datetime(df["Date"])

In [7]:
# Add a "day of the week" column by extracting the weekday property of the dt property 
# of the Date column and place it into the 'day of the week' column

df["day of the week"] = df["Date"].dt.weekday
df[["Date","day of the week"]].head(15)

         Date  day of the week
0  2020-04-03                4
1  2020-04-13                0
2  2020-07-10                4
3  2020-09-02                2
4  2020-10-31                5
5  2020-04-14                1
6  2020-05-14                3
7  2020-07-04                5
8  2020-08-05                2
9  2020-11-20                4
10 2020-06-21                6
11 2020-08-10                0
12 2020-10-01                3
13 2020-10-21                2
14 2020-11-05                3